image: docker

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - fortiss-di
  - fortiss-robotics
  - kuka-iiwa

build_fortiss_di:
  stage: fortiss-di
  script:
    - docker run \
      --mount type=bind,source=$(pwd),target=/model/src \
      --entrypoint "/app/PublishModel.sh" \
      sailavid/ua-modelcompiler \
       /model/src/fortiss_di/fortissDiModel fortiss_di /model/src/Published
  artifacts:
    paths:
    - Published

build_fortiss_robotics:
  stage: fortiss-robotics
  script:
    - docker run \
      --mount type=bind,source=$(pwd),target=/model/src \
      --entrypoint "/app/PublishModel.sh" \
      sailavid/ua-modelcompiler \
       /model/src/fortiss_robotics/fortissRoboticsModel fortiss_robotics /model/src/Published
  artifacts:
    paths:
    - Published

build_kuka_iiwa:
  stage: kuka-iiwa
  script:
    - docker run \
      --mount type=bind,source=$(pwd),target=/model/src \
      --entrypoint "/app/PublishModel.sh" \
      sailavid/ua-modelcompiler \
       /model/src/kuka_iiwa/kukaIiwaModel kuka_iiwa /model/src/Published
  artifacts:
    paths:
    - Published
